version: "3.9"

services:
  backend:
    build: ./backend
    container_name: aasare-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - frontend
    restart: always

  frontend:
    build: ./frontend
    container_name: aasare-frontend
    ports:
      - "3000:80"
    stdin_open: true
    tty: true
    restart: always
